modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="create_embedded_freights"
version="\${version}"
displayName="Create: Embedded Freights"
authors="Aether_254"
description='''Changes the Create packager so complete packages can be packed as items inside new packages, with configurable package-depth and NBT-depth safety limits.'''

[[dependencies.create_embedded_freights]]
modId="forge"
mandatory=true
versionRange="[47.1.33,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_embedded_freights]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.create_embedded_freights]]
modId="create"
mandatory=true
versionRange="[6.0.8,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_embedded_freights]]
modId="cloth_config"
mandatory=true
versionRange="[11.1.136,)"
ordering="AFTER"
side="BOTH"

