modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="create_embedded_freights"
version="\${version}"
displayName="Create: Embedded Freights"
authors="Aether_254"
description='''Changes the Create packager so complete packages can be packed as items inside new packages, with configurable package-depth and NBT-depth safety limits.'''

[[mixins]]
config="create_embedded_freights.mixins.json"

[[dependencies.create_embedded_freights]]
modId="neoforge"
type="required"
versionRange="[21.1.219,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_embedded_freights]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH"

[[dependencies.create_embedded_freights]]
modId="create"
type="required"
versionRange="[6.0.11,)"
ordering="AFTER"
side="BOTH"

[[dependencies.create_embedded_freights]]
modId="cloth_config"
type="required"
versionRange="[15.0.140,)"
ordering="AFTER"
side="BOTH"

